=== sharathandroid/studentjaxb/src/main/resources/xsd/Student.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Student" xmlns:tns="http://www.example.org/Student" elementFormDefault="qualified">


    <complexType name="Student">
    	<sequence>
    		<element name="studentId" type="int"></element>
    		<element name="name" type="string"></element>
    		<element name="marks" type="tns:Marks" minOccurs="1"
    			maxOccurs="unbounded">
    		</element>
    		<element name="address" type="tns:Address"></element>
    	</sequence>
    </complexType>
    <complexType name="Address">
    	<sequence>
    		<element name="street" type="string"></element>
    		<element name="state" type="string"></element>
    		<element name="zipcode" type="int"></element>
    		<element name="type">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="HOME"></enumeration>
    					<enumeration value="COMMUNICATION"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
    	</sequence>
    </complexType>
    
    <complexType name="Marks">
    	<sequence>
    		<element name="subject" type="string"></element>
    		<element name="marks" type="double"></element>
    		<element name="maxMarks" type="double"></element>
    	</sequence>
    </complexType>


    <element name="Element" type="tns:Student"></element>
</schema>

=== sharathandroid/studentjaxb/src/main/resources/xml/Student.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Element xmlns:tns="http://www.example.org/Student" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Student ../xsd/Student.xsd ">
  <tns:studentId>0</tns:studentId>
  <tns:name>tns:name</tns:name>
  <tns:marks>
    <tns:subject>tns:subject</tns:subject>
    <tns:marks>0.0</tns:marks>
    <tns:maxMarks>0.0</tns:maxMarks>
  </tns:marks>
  <tns:address>
    <tns:street>tns:street</tns:street>
    <tns:state>tns:state</tns:state>
    <tns:zipcode>0</tns:zipcode>
    <tns:type>HOME</tns:type>
  </tns:address>
</tns:Element>
